asset_dir = "assets"
exclude_assets = ["*.luau", "*.rbxm"]
write_dir = "assets"

[creator]
type = "user"
id = 1 # replace with your id

[codegen]
output_name = "assets"
typescript = false
style = "nested"
strip_extension = true
